# Generated by Django 4.0.3 on 2023-04-17 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0002_category_fooditem_userfooditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userfooditem',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='userfooditem',
            name='fooditem',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Fooditem',
        ),
        migrations.DeleteModel(
            name='UserFooditem',
        ),
    ]
